import React from 'react';
import {
  DollarSign,
  TrendingUp,
  PieChart,
  Users,
  CheckCircle2,
  AlertCircle,
  FileText,
  Calculator,
  Percent,
} from 'lucide-react';
import { Modal } from '../common/Modal';
import { ManagedAsset } from '../../types';
import { formatCurrency } from '../../utils/formatters';
import {
  calculateAssetPartnerShares,
  getOwnershipModelBadgeStyle,
  getOwnershipModelLabel,
} from '../../utils/assetCalculations';

interface AssetProfitabilityModalProps {
  isOpen: boolean;
  onClose: () => void;
  asset: ManagedAsset | null;
  currency: string;
  onOpenSettlement?: (asset: ManagedAsset) => void;
}

export const AssetProfitabilityModal: React.FC<AssetProfitabilityModalProps> = ({
  isOpen,
  onClose,
  asset,
  currency,
  onOpenSettlement,
}) => {
  if (!asset) return null;

  const partnerShares = calculateAssetPartnerShares(asset);
  const profitMargin =
    asset.totalRevenue > 0
      ? Math.round((asset.netProfit / asset.totalRevenue) * 100)
      : 0;

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Profitability & Financial Distribution: ${asset.name}`}
      subtitle={`${asset.assetNumber} · ${getOwnershipModelLabel(asset.ownershipModel)}`}
      maxWidth="3xl"
    >
      <div className="space-y-6 text-xs text-slate-700">
        {/* Top Summary Row */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-4 bg-slate-50 rounded-xl border border-slate-200">
          <div>
            <span className="text-[11px] text-slate-500 font-medium">Total Asset Revenue</span>
            <div className="text-lg font-bold font-mono text-slate-900 mt-0.5 tabular-nums">
              {formatCurrency(asset.totalRevenue, currency)}
            </div>
            <span className="text-[10px] text-emerald-600 font-medium">Generated by work orders</span>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 font-medium">Total Asset Expenses</span>
            <div className="text-lg font-bold font-mono text-rose-700 mt-0.5 tabular-nums">
              {formatCurrency(asset.totalExpenses, currency)}
            </div>
            <span className="text-[10px] text-slate-400">
              Shared: {formatCurrency(asset.sharedExpenses, currency)} · Direct: {formatCurrency(asset.directExpenses, currency)}
            </span>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 font-medium">Net Realized Profit</span>
            <div className="text-lg font-bold font-mono text-emerald-700 mt-0.5 tabular-nums">
              {formatCurrency(asset.netProfit, currency)}
            </div>
            <span className="text-[10px] text-emerald-700 font-semibold bg-emerald-50 px-1 rounded border border-emerald-200">
              {profitMargin}% net margin
            </span>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 font-medium">Outstanding Balances</span>
            <div className="text-lg font-bold font-mono text-amber-700 mt-0.5 tabular-nums">
              {formatCurrency(asset.outstandingPayments, currency)}
            </div>
            <span className="text-[10px] text-slate-500">Unsettled partner payables</span>
          </div>
        </div>

        {/* Expense Allocation Model Explainer */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="p-4 bg-white rounded-xl border border-slate-200/90 shadow-2xs space-y-2">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="font-bold text-slate-900 text-xs flex items-center gap-1.5">
                <PieChart className="w-4 h-4 text-blue-600" />
                Shared Expenses Allocation
              </span>
              <span className="font-mono font-bold text-slate-900">
                {formatCurrency(asset.sharedExpenses, currency)}
              </span>
            </div>
            <p className="text-[11px] text-slate-500">
              Fuel, maintenance, insurance, and routine fleet upkeep distributed automatically
              according to configured ownership/expense percentage ratios.
            </p>
          </div>

          <div className="p-4 bg-white rounded-xl border border-slate-200/90 shadow-2xs space-y-2">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="font-bold text-slate-900 text-xs flex items-center gap-1.5">
                <FileText className="w-4 h-4 text-purple-600" />
                Direct Expenses Allocation
              </span>
              <span className="font-mono font-bold text-slate-900">
                {formatCurrency(asset.directExpenses, currency)}
              </span>
            </div>
            <p className="text-[11px] text-slate-500">
              Permits, specific fines, lease payments, or partner-specific costs charged directly
              without percentage distribution.
            </p>
          </div>
        </div>

        {/* Sharing Agreement Specification */}
        {asset.sharingAgreement && (
          <div className="p-3 bg-blue-50/60 rounded-xl border border-blue-200 flex items-start gap-2.5">
            <Calculator className="w-4 h-4 text-blue-600 mt-0.5 shrink-0" />
            <div>
              <div className="font-bold text-blue-900">
                Configured Agreement: {asset.sharingAgreement.method.replace('_', ' ').toUpperCase()}
              </div>
              <p className="text-[11px] text-blue-800 mt-0.5">
                {asset.sharingAgreement.customRulesDescription ||
                  'Net profit after expenses is allocated according to partner percentages.'}
              </p>
            </div>
          </div>
        )}

        {/* Partner Distribution Payout Ledger */}
        <div className="bg-white rounded-xl border border-slate-200/90 shadow-2xs overflow-hidden">
          <div className="px-4 py-3 bg-slate-50 border-b border-slate-100 flex items-center justify-between">
            <span className="font-bold text-slate-900 text-xs flex items-center gap-2">
              <Users className="w-4 h-4 text-slate-600" />
              Partner / Owner Distribution Schedule
            </span>
            <span className="text-[11px] text-slate-500">
              {partnerShares.length} participating stakeholder{partnerShares.length !== 1 ? 's' : ''}
            </span>
          </div>

          {partnerShares.length === 0 ? (
            <div className="p-6 text-center text-slate-500 text-xs">
              No shared partners registered. This asset is 100% company-owned or under fixed lease.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-100 text-slate-400 font-semibold bg-slate-50/50">
                    <th className="py-2.5 px-3">Partner / Shareholder</th>
                    <th className="py-2.5 px-3 text-center">Share %</th>
                    <th className="py-2.5 px-3 text-right">Revenue Share</th>
                    <th className="py-2.5 px-3 text-right">Shared Exp. Share</th>
                    <th className="py-2.5 px-3 text-right">Direct Costs</th>
                    <th className="py-2.5 px-3 text-right">Net Profit Share</th>
                    <th className="py-2.5 pr-3 text-right">Amount Payable</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {partnerShares.map((share) => (
                    <tr key={share.partnerId} className="hover:bg-slate-50/60 transition-colors">
                      <td className="py-3 px-3">
                        <div className="font-semibold text-slate-900">{share.partnerName}</div>
                      </td>
                      <td className="py-3 px-3 text-center font-mono font-bold text-blue-700">
                        {share.ownershipPercentage}%
                      </td>
                      <td className="py-3 px-3 text-right font-mono tabular-nums text-slate-700">
                        {formatCurrency(share.revenueShareAmount, currency)}
                      </td>
                      <td className="py-3 px-3 text-right font-mono tabular-nums text-rose-700">
                        -{formatCurrency(share.expenseShareAmount, currency)}
                      </td>
                      <td className="py-3 px-3 text-right font-mono tabular-nums text-slate-600">
                        {share.directExpensesIncurred > 0 ? (
                          <span className="text-amber-700">
                            -{formatCurrency(share.directExpensesIncurred, currency)}
                          </span>
                        ) : (
                          '$0.00'
                        )}
                      </td>
                      <td className="py-3 px-3 text-right font-mono font-bold tabular-nums text-emerald-700">
                        {formatCurrency(share.netProfitShareAmount, currency)}
                      </td>
                      <td className="py-3 pr-3 text-right font-mono font-extrabold tabular-nums text-sm text-blue-700">
                        {formatCurrency(share.netPayableAmount, currency)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="pt-3 border-t border-slate-100 flex items-center justify-between">
          <div className="text-[11px] text-slate-500">
            Historical transaction ledger preserved · Calculations update dynamically
          </div>

          <div className="flex items-center gap-2">
            {onOpenSettlement && (
              <button
                onClick={() => {
                  onClose();
                  onOpenSettlement(asset);
                }}
                className="px-3.5 py-1.5 rounded-lg border border-amber-300 bg-amber-50 hover:bg-amber-100 text-amber-900 font-semibold text-xs transition-colors cursor-pointer"
              >
                Close / Final Settlement
              </button>
            )}
            <button
              onClick={onClose}
              className="px-4 py-1.5 rounded-lg bg-slate-900 text-white font-medium hover:bg-slate-800 transition-colors cursor-pointer"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </Modal>
  );
};
